/* Simulador ligero: DOM/CSS, sin canvas ni bucles de trayectoria. */
(()=>{
let current=0,state=null;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const practiceInfo={
  1:{title:'Movimiento X / Y',steps:['Enciende el control con ON.','Selecciona JOG.','Pulsa X+ o X− una vez.','Pulsa Y+ o Y− una vez.'],next:'Ya conoces el movimiento básico en X/Y.'},
  2:{title:'Movimiento X / Y / Z',steps:['Enciende el control con ON.','Selecciona JOG.','Mueve X.','Mueve Y.','Mueve Z.'],next:'Ya puedes identificar los tres ejes.'},
  3:{title:'Maquinado final',steps:['Pulsa ON.','Pulsa SIMULAR para revisar la trayectoria.','Pulsa CYCLE START.','Espera a que termine el ciclo.'],next:'¡Maquinado didáctico terminado!'}
};
function render(n){current=n;const info=practiceInfo[n];state={on:false,mode:'OFF',x:0,y:0,z:50,moved:{x:false,y:false,z:false},sim:false,running:false,done:false};
const sim=document.querySelector('#sim');sim.hidden=false;sim.innerHTML=`<div class="sim-header"><div><span class="eyebrow">SIMULADOR DIDÁCTICO</span><h2>Práctica ${n}: ${info.title}</h2><p>Representación visual para aprender; no controla una máquina real.</p></div><button class="sim-close" type="button">Cerrar</button></div>
<div class="machine-sim"><div class="machine-photo"><img src="img/maquina.jpg" alt="DATAN ME500"><div class="tool-dot" id="toolDot"></div><div class="axis-overlay"><span>X</span><span>Y</span><span>Z</span></div><div class="sim-status" id="machineStatus">APAGADO</div></div><div class="sim-panel"><div class="fake-screen"><div class="screen-title">SINUMERIK 808D</div><div class="dro-row"><b>X</b><span id="dx">0.0</span></div><div class="dro-row"><b>Y</b><span id="dy">0.0</span></div><div class="dro-row"><b>Z</b><span id="dz">50.0</span></div><div class="screen-state" id="screenState">APAGADO</div></div><div class="control-buttons"><button data-a="on">ON</button><button data-a="jog">JOG</button><button data-a="x+">X+</button><button data-a="x-">X−</button><button data-a="y+">Y+</button><button data-a="y-">Y−</button><button data-a="z+">Z+</button><button data-a="z-">Z−</button>${n===3?'<button data-a="sim" class="wide">▶ SIMULAR</button><button data-a="cycle" class="wide cycle">⏵ CYCLE START</button>':''}</div></div></div>
<div class="sim-bottom"><div><h3>Pasos</h3><ol id="simSteps">${info.steps.map((s,i)=>`<li data-step="${i}">${s}</li>`).join('')}</ol></div><div class="sim-message" id="simMessage">Empieza con el primer paso.</div></div>`;
sim.querySelector('.sim-close').addEventListener('click',()=>{sim.hidden=true;sim.innerHTML='';});
sim.addEventListener('click',handle);update();sim.scrollIntoView({behavior:'smooth',block:'start'});}
function handle(e){const b=e.target.closest('button');if(!b)return;const a=b.dataset.a;if(a==='on'){state.on=true;state.mode='JOG';}else if(a==='jog'){if(state.on)state.mode='JOG';}else if(a==='x+'||a==='x-'){if(!ready())return;state.x=clamp(state.x+(a==='x+'?10:-10),-50,100);state.moved.x=true;}else if(a==='y+'||a==='y-'){if(!ready())return;state.y=clamp(state.y+(a==='y+'?10:-10),-50,100);state.moved.y=true;}else if(a==='z+'||a==='z-'){if(!ready())return;state.z=clamp(state.z+(a==='z+'?10:-10),0,80);state.moved.z=true;}else if(a==='sim'&&current===3){if(!state.on)return message('Primero pulsa ON.');state.sim=true;}else if(a==='cycle'&&current===3){if(!state.sim)return message('Primero revisa la simulación.');state.running=true;message('Ejecutando el contorno didáctico…','info');setTimeout(()=>{state.done=true;state.running=false;message('✓ Ciclo terminado. Práctica completada.','good');complete();update();},900);}update();}
function ready(){if(!state.on){message('Pulsa ON primero.');return false;}if(state.mode!=='JOG'){message('Pulsa JOG para mover los ejes.');return false;}return true;}
function message(t,c='bad'){const m=document.querySelector('#simMessage');if(m){m.textContent=t;m.className='sim-message '+c;}}
function update(){if(!state)return;document.querySelector('#dx').textContent=state.x.toFixed(1);document.querySelector('#dy').textContent=state.y.toFixed(1);document.querySelector('#dz').textContent=state.z.toFixed(1);document.querySelector('#machineStatus').textContent=state.running?'CICLO EN EJECUCIÓN':state.on?'ENCENDIDA':'APAGADO';document.querySelector('#screenState').textContent=state.mode+(state.sim?' · SIMULACIÓN':'');const dot=document.querySelector('#toolDot');dot.style.left=`${50+state.x/4}%`;dot.style.top=`${52-state.y/5}%`;dot.style.transform=`translate(-50%,-50%) scale(${state.z<20?1.25:1})`;if(current===3&&state.sim)document.querySelector('.machine-photo').classList.add('simulated');
const doneSteps=current===1?[state.on,state.mode==='JOG',state.moved.x,state.moved.y]:current===2?[state.on,state.mode==='JOG',state.moved.x||state.moved.y,state.moved.y,state.moved.z]:[state.on,state.sim,state.running||state.done,state.done];document.querySelectorAll('#simSteps li').forEach((li,i)=>{li.classList.toggle('ok',!!doneSteps[i]);li.classList.toggle('now',!doneSteps[i]&&doneSteps.slice(0,i).every(Boolean));});if(doneSteps.every(Boolean)&&current!==3)complete();}
function complete(){if(!window.markPractice)return;window.markPractice(current);document.querySelectorAll('.practice').forEach((p,i)=>{if(i+1===current){p.classList.add('done');p.classList.remove('locked');}});setTimeout(()=>{const btn=document.querySelector(`#practice${current} .sim-start`);if(btn){btn.textContent='✓ Completada';btn.disabled=true;}},0);}
document.addEventListener('click',e=>{const b=e.target.closest('.sim-start');if(b&&!b.disabled&&!b.closest('.locked'))render(Number(b.dataset.p));});
})();
